# docker-compose -f docker-compose.base.yml -f docker-compose.build.yml -f docker-compose.testing.yml up --abort-on-container-exit go-vue-blog.node.testing
version: '2'

services:
  go-vue-blog.api:
    environment:
    - MONGO_DB=go-vue-blog-testing

  go-vue-blog.node.testing:
    image: alekzonder/puppeteer:1.1.1
    volumes:
    - ../../frontend:/app
    container_name: go-vue-blog-node-testing
    environment:
    - TESTING_HEADLESS=true
    - TESTING_URL=http://go-vue-blog.nginx
    networks: [go-vue-blog]
# npm i - optional, if failed - probably node_modules exist
    command: [sh, -c, "cd /app && (npm i || echo 'go-vue-blog.node.testing: fail npm i') && npm run test"]
